---
- hosts: all
  tasks:
    - name: install docker
      yum: name=docker state=present
      tags: a
    - name: start docker
      service: name=docker state=started
      tags: b
    - name: install maven
      yum: name=maven state=present
      tags: c
    - name: create user
      user: name=raja state=present
      tags: d    
